version: '3'
services: 
    productapi:
        build: GRPCGREETER/
        ports: 
        - "8000:80"
        - "8001:443"
        environment: 
            ASPNETCORE_URLS: "https://+;http://+"
            ASPNETCORE_HTTPS_PORT: "8001"
            ASPNETCORE_ENVIROMENT: Development
        volumes: 
           - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
           - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
