version: '3'
services: 
    productapi:
        build: GRPCGREETER/
        ports: 
        - "8000:80"
        - "8001:443"
        environment: 
            - ASPNETCORE_URLS=https://0.0.0.0:5000
            - ASPNETCORE_HTTPS_PORT=5000
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/servercert.pfx
        # volumes: 
        #    - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
        #    - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/ 
